services:
  - type: web
    name: n8n-service
    env: docker
    repo: https://github.com/LemontZ23/n8n-render-deploy2
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          name: n8n-db
          type: postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          name: n8n-db
          type: postgres
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          name: n8n-db
          type: postgres
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          name: n8n-db
          type: postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          name: n8n-db
          type: postgres
          property: password
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your_secure_password_here
      - key: N8N_HOST
        value: n8n-service-oqjn.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-service-oqjn.onrender.com/
      - key: N8N_PORT
        value: "5678"
      - key: NODE_ENV
        value: production

  - type: postgres
    name: n8n-db
    plan: free
